---
title: "Investigadora Ana Figueiredo participa en Congreso de Psicología en Buenos Aires"
date: "18 Diciembre 2023"
image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=1200&h=600&fit=crop"
author: "ana, pinto_matias_e, nicolas_tobar"
tags: ["Noticias", "Investigación", "Ponencias"]
destacado: false
tipo: "noticia"
---

SIMPOSIO| El pasado 1 de diciembre Ana Figueiredo, investigadora de OLES, participó en el XV Congreso internacional de Investigación y Práctica Profesional en Psicología, organizado por la Universidad de Buenos Aires. En este contexto, Ana expuso su trabajo en el simposio internacional Memoria Colectiva e Identidad Social, el cual tiene por titulo “Las conexiones entre ideologías postcoloniales y las demandas de reparación y reconocimiento hacia el pueblo Mapuche”. Este consistió en un estudio cualitativo con 29 personas Mapuche, donde se trabajaron distintas ideologías postcoloniales y la manera en que son percibidas las demandas de reparación y reconocimiento del pueblo Mapuche en la actualidad.

¡Revisa el simposio en el siguiente link!

[https://www.youtube.com/watch?v=BPiHYwFGpWk](https://www.youtube.com/watch?v=BPiHYwFGpWk&t=3685s)

